django_rest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('restful_api.urls', namespace='api')),
    path('', include('js_frontend.urls', namespace='frontend')),

]

js_frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.list, name='list'),
]

restful_api/urls.py
from django.urls import path

app_name = 'api'
from . import views
urlpatterns = [
    path('', views.apiOverview, name='api-overview'),
    path('task-list/', views.taskList, name='task-list'),
    path('task-detail/<int:pk>/', views.taskDetail, name='task-detail'),
    path('task-create/', views.taskCreate, name='task-create'),
    path('task-update/<int:pk>/', views.taskUpdate, name='task-update'),
    path('task-delete/<int:pk>/', views.taskDelete, name='task-delete'),

]

js_frontend/models.py
from django.db import models

# Create your models here.

restful_api/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.title

js_frontend/views.py
from django.shortcuts import render

# Create your views here.
def list(request):
    return render(request, 'js_frontend/list.html')

restful_api/views.py
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from . models import Task
from .serializers import TaskSerializer
# Create your views here.

@api_view(['GET'])
def apiOverview(request):
    api_url = {
        'List': '/task-list/',
        'Detail View': '/task-detail/<str:pk>/',
        'Create': '/task-create/',
        'Update': '/task-delete/<str: pk/',

    }
    return Response(api_url)


@api_view(['GET'])
def taskList(request):
    tasks = Task.objects.all().order_by('-id')
    serializer = TaskSerializer(tasks, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def taskDetail(request, pk):
    tasks = Task.objects.get(id=pk)
    serializer = TaskSerializer(tasks, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def taskCreate(request):
    serializer = TaskSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['POST'])
def taskUpdate(request, pk):
    task = Task.objects.get(id=pk)
    serializer = TaskSerializer(instance=task, data=request.data)

    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['DELETE'])
def taskDelete(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    return Response('Item Deleted Successfully')

js_frontend/templates/js_frontend/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TO DO</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

    <style>
        body{
		  background: rgb(54,217,182);
		  background: linear-gradient(90deg, rgba(54,217,182,1) 0%, rgba(32,152,126,1) 43%, rgba(0,212,255,1) 100%);
		}

        h1, h2, h3, h4, h5, p, span, strike {
            font-family: 'Montserrat', sans-serif;
        }

        #task-container{
		  max-width:600px;
		  margin:0 auto;
		  box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
		  background-color: #fff;

		  margin-top:100px;
		  margin-bottom:100px;

		  justify-content: space-around;
		  align-items: flex-start;

		}

		#form-wrapper{
		  position: -webkit-sticky;
		  position: sticky;
		  top: 0rem;
		  border-bottom: 1px solid  #e9e9e9;
		  background-color: #fff;
		  box-shadow: 0 3px 8px rgba(0,0,0,0.25);
 		  padding:40px;
		}

		#submit{
		  background-color: #36d9b6;
		  border-radius: 0;
		  border:0;
		  color: #fff;
		}

		.flex-wrapper{
			display: flex;
		}

		.task-wrapper{
		  	margin:5px;
		  	padding: 5px;
		  	padding:20px;
		  	cursor: pointer;
		  	border-bottom: 1px solid  #e9e9e9;
		  	color: #686868;
        }
    </style>
</head>
<body>
    <div class="container">

		<div id="task-container">
			<div id="form-wrapper">
				<form id="form">
					<div class="flex-wrapper">
						<div style="flex: 6">
							<input id="title" class="form-control" type="text" name="title" placeholder="Add task">
						</div>
						<div style="flex: 1">
							<input id="submit" class="btn" type="submit" >
						</div>
					</div>
				</form>
			</div>

			<div id="list-wrapper">

			</div>
		</div>

	</div>

    <script>
        /*
			KEY COMPONENTS:
			"activeItem" = null until an edit button is clicked. Will contain object of item we are editing
			"list_snapshot" = Will contain previous state of list. Used for removing extra rows on list update

			PROCESS:
			1 - Fetch Data and build rows "buildList()"
			2 - Create Item on form submit
			3 - Edit Item click - Prefill form and change submit URL
			4 - Delete Item - Send item id to delete URL
			5 - Cross out completed task - Event handle updated item
			NOTES:
			-- Add event handlers to "edit", "delete", "title"
			-- Render with strike through items completed
			-- Remove extra data on re-render
			-- CSRF Token
		*/

		function getCookie(name) {
			let cookieValue = null;
    		if (document.cookie && document.cookie !== '') {
        		const cookies = document.cookie.split(';');
        		for (let i = 0; i < cookies.length; i++) {
            		const cookie = cookies[i].trim();
            		// Does this cookie string begin with the name we want?
            		if (cookie.substring(0, name.length + 1) === (name + '=')) {
                		cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                		break;
            		}
        		}
    		}
    		return cookieValue;
		}
		const csrftoken = getCookie('csrftoken');


		// function to list all available tasks

		var activeItem = null
        function buildList() {
        	var wrapper = document.getElementById('list-wrapper')
			wrapper.innerHTML = ''	//to clear out existing list display on each new wrapper

			var url = "{% url 'api:task-list' %}"	//'http://127.0.0.1:8080/api/task-list'
			fetch(url)
			.then((resp) => resp.json())
			.then(function (data) {
				console.log('Data', data)

				// display list data in html
				var list = data
				for (var i in list) {
					var item = `
						<div id="data-row-${i}" class="task-wrapper flex-wrapper">
							<div style="flex: 7">
								<span class="title">${list[i].title}</span>
							</div>

							<div style="flex: 1">
								<button class="btn btn-sm btn-outline-info edit">Edit</button>
							</div>

							<div style="flex: 7">
								<button class="btn btn-sm btn-outline-dark delete">Delete</button>
							</div>
						</div>

					`
					wrapper.innerHTML += item
				}
				// grab each task for editing
				for (var i in list) {
					var editBtn = document.getElementsByClassName('edit')[i]
					editBtn.addEventListener('click', (function (item) {
						return function (){
							editItem(item)
						}
					})(list[i]))
				}
			})
		}
		buildList()

		// create new task
		var form = document.getElementById('form-wrapper')
		form.addEventListener('submit', function (e) {
			e.preventDefault()
			console.log('Form Submitted')
			var url = "{% url 'api:task-create' %}"

			if (activeItem != null) {
				var url = `http://127.0.0.1:8080/api/task-update/${activeItem.id}/`
				activeItem = null
			}
			var title = document.getElementById('title').value

			fetch(url, {
				method: 'POST',
				headers: {
					'Content-type': 'application/json',
					'X-CSRFToken': csrftoken
				},
				body: JSON.stringify({'title': title})	// request.data in taskCreate view
			}).then(function (response){
				buildList()
				document.getElementById('form').reset()
			})
		})


		// function to edit task
		function editItem(item){
        	console.log('Item clicked', item)
			activeItem = item	// set activeItem as the current item chosen
			document.getElementById('title').value = activeItem.title
		}
    </script>
</body>
</html>